#include <iostream>
#include <vector>

#pragma once

struct MusicKit_t
{
    uint16_t id;
    std::string name;
    std::string image_url = "";
    
    MusicKit_t(uint16_t _id, std::string _name, std::string _img = "") : id(_id), name(_name), image_url(_img) {}
};

enum class MusicKit : uint16_t
{
    CounterStrike2 = 1,
    MusicNotNamed,
    CrimsonAssault,
    Sharpened,
    Insurgency,
    A_D_8,
    HighNoon,
    DeathsHeadDemolition,
    DesertFire,
    LNOE,
    Metal,
    AllIWantForChristmas,
    IsoRhythm,
    ForNoMankind,
    HotlineMiami,
    The8BitKit,
    TheTalosPrinciple,
    Battlepack,
    Molotov,
    UberBlastoPhone,
    HazardousEnvironments,
    Headshot,
    TotalDomination,
    IAm,
    Diamonds,
    Invasion,
    LionsMouth,
    SpongeFingerz,
    Aggressive,
    JavaHavanaFunkaloo,
    MomentsCSGO,
    Disgusting,
    TheGoodYouth,
    Free,
    LifesNotOutToGetYou,
    Backbone,
    GLA,
    Arena,
    EZ4ENCE,
    Halo,
    KingScar,
    AlxyAntiCitizen,
    Bachram,
    TacoTruck,
    EyeOfTheDragon,
    MUDDForce,
    NeoNoir,
    Bodacious,
    Drifter,
    AllForDust,
    Hades,
    TheLowfilePack,
    ChainsawLxadxut,
    MochaPetal,
    YellowMagic,
    Vici,
    AtroBellum,
    WorkHardPlayHard,
    Kolibri,
    U_Mad,
    FlashBangDance,
    HeadingForTheSource,
    Void,
    Shooters,
    Dashstar,
    GothicLuxury,
    LockMeUp,
    HuaLian,
    Ultimate,
    CSGO,
    UnderBrightLights = 76,
    Dashstar_New = 77,
    TheDevilWentClubbingInGeorgia = 78,
    GothicLuxury_New = 79,
    UMad_New = 82,
    HeadingForTheSource_New = 83,
    Void_New = 84,
    SeventhMoon = 85,
    Shooters_New = 86,
    RedRoom = 87,
    Skeleta = 88,
    RATWARS = 89,
    ChewingGlass = 90,
    StarshipVelociraptor = 91,
    Floorspace = 92,
    MICHAEL = 93,
    Evergreen = 94,
    NoLoveOnlyPleasure = 95,
    ThePerfumeOfDecay = 96,
    DOPAMINEHIT = 97,
    ChangeMyMind = 98,
    GiveItToMe = 99,
    EVERYNITE = 100,
    OnAndOn = 101,
    Voices = 102
};

static std::vector<MusicKit_t> musicKits =
{
    { MusicKit_t(static_cast<uint16_t>(MusicKit::CounterStrike2),        "Counter-Strike 2") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::MusicNotNamed),         "Valve CSGO 2 (hidden)") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::CrimsonAssault),        "Crimson Assault") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Sharpened),             "Sharpened") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Insurgency),            "Insurgency") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::A_D_8),                 "A_D_8") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::HighNoon),              "High Noon") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::DeathsHeadDemolition),  "Death's Head Demolition") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::DesertFire),            "Desert Fire") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::LNOE),                  "LNOE") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Metal),                 "Metal") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::AllIWantForChristmas),  "All I Want For Christmas") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::IsoRhythm),             "Iso Rhythm") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::ForNoMankind),          "For No Mankind") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::HotlineMiami),          "Hotline Miami") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::The8BitKit),            "The 8-Bit Kit") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TheTalosPrinciple),     "The Talos Principle") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Battlepack),            "Battlepack") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Molotov),               "Molotov") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::UberBlastoPhone),       "Uber Blasto Phone") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::HazardousEnvironments), "Hazardous Environments") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Headshot),              "Headshot") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TotalDomination),       "Total Domination") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::IAm),                   "I Am") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Diamonds),              "Diamonds") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Invasion),              "Invasion!") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::LionsMouth),            "Lion's Mouth") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::SpongeFingerz),         "Sponge Fingerz") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Aggressive),            "Aggressive") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::JavaHavanaFunkaloo),    "Java Havana Funkaloo") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::MomentsCSGO),           "Moments CSGO") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Disgusting),            "Disgusting") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TheGoodYouth),          "The Good Youth") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Free),                  "FREE") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::LifesNotOutToGetYou),   "Life's Not Out To Get You") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Backbone),              "Backbone") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::GLA),                   "GLA") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Arena),                 "Arena") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::EZ4ENCE),               "EZ4ENCE") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Halo),                  "Halo") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::KingScar),              "King, Scar") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::AlxyAntiCitizen),       "Anti-Citizen") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Bachram),               "Bachram") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TacoTruck),             "Taco Truck") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::EyeOfTheDragon),        "Eye of the Dragon") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::MUDDForce),             "M.U.D.D. FORCE") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::NeoNoir),               "Neo Noir") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Bodacious),             "Bodacious") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Drifter),               "Drifter") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::AllForDust),            "All For Dust") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Hades),                 "Hades") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TheLowfilePack),        "The Lowfile Pack") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::ChainsawLxadxut),       "CHAINSAW Lxadxut") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::MochaPetal),            "Mocha Petal") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::YellowMagic),           "Yellow Magic") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Vici),                  "VICI") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::AtroBellum),            "Atro Bellum") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::WorkHardPlayHard),      "Work Hard, Play Hard") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Kolibri),               "Kolibri") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::UMad_New),              "U Mad!") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::FlashBangDance),        "Flashbang Dance") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::HeadingForTheSource_New), "Heading For The Source") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Void_New),               "Void") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Shooters_New),           "Shooters") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Dashstar_New),           "Dashstar*")},
    { MusicKit_t(static_cast<uint16_t>(MusicKit::GothicLuxury_New),       "Gothic Luxury") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::LockMeUp),              "Lock Me Up") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::HuaLian),               "Hua Lian") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Ultimate),              "Ultimate") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::UnderBrightLights),     "Under Bright Lights") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::CSGO),                  "CS:GO") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TheDevilWentClubbingInGeorgia), "The Devil Went Clubbing in Georgia") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::SeventhMoon),           "Seventh Moon") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::RedRoom),               "Red Room") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Skeleta),               "Skeletá") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::RATWARS),               "RAT WARS") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::ChewingGlass),           "Chewing Glass") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::StarshipVelociraptor),   "Starship Velociraptor") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Floorspace),             "Floorspace") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::MICHAEL),                "MICHAEL") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Evergreen),              "Evergreen") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::NoLoveOnlyPleasure),     "No Love Only Pleasure") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::ThePerfumeOfDecay),      "The Perfume of Decay") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::DOPAMINEHIT),            "DOPAMINE HIT") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::ChangeMyMind),           "Change My Mind") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::GiveItToMe),            "Give It To Me") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::EVERYNITE),              "EVERYNITE") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::OnAndOn),                "On And On") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Voices),                 "Voices") }
};
